#define USE_ORIGINAL_ENGINE_SELECTION 0
#define USE_BOUNDARY_OPT_ON_GEOMOPT 1
#define USE_BOUNDARY_OPT_ON_MOLDYN 1

// режимы работы консольного приложения example4
// запуск снаряда по цели: нагретой или при Т = 0 К
#define SNARJAD_TARGET_WORKING 0
#define SNARJAD_TARGET_WORKING_T_0 0
// перемещение фиксируемого пробного атома 
// при включённой молекулярной динамике мембраны, 
// находящейся при температуре, исследование сил, действующих на пробный атом
#define PROBNIY_ATOM_WORKING 0

// перемещение фиксируемого пробного атома 
// с оптимизацией геометрии мембраны
// исследование потенциального барьера
#define PROBNIY_ATOM_GEOMOPT 0
#define PROBNIY_ATOM_GEOMOPT_TRADITIONAL 0
#define USE_BOUNDARY_OPT_ON_PROBNIY_ATOM_GEOMOPT 0

// режим работы с наложением броуновского осциллятора 
// в виде гравитационной осцилляции
#define GRAVI_OSCILLATOR_WORKING 1
#define GRAVI_OSCILLATOR_WORKING_LINEAR 1
#define GRAVI_OSCILLATOR_START_ON_T_USTANOV 1

#define KLAPAN_DIFFUSE_WORKING 1
#define MOLDYN_LOCK_ATOMS_ONLY_ON_Z_DIM 1

#define DIFFUSE_WORKING 0

/* src/libconfig.h.  Generated by configure.  */
/* src/libconfig.h.in.  Generated from configure.ac by autoheader.  */

/* Define if you are building a version that interfaces directly with MOPAC7
   */
/* #undef ENABLE_MOPAC7 */
#define ENABLE_MOPAC7 1

/* Define if you are building a version that interfaces directly with MPQC */
/* #undef ENABLE_MPQC */
//#define ENABLE_MPQC 1

/* Define if you are building a version that interfaces directly with
   OpenBabel */
/* #undef ENABLE_OPENBABEL */
#define ENABLE_OPENBABEL 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `blas' library (-lblas). */
/* #undef HAVE_LIBBLAS */

/* Define to 1 if you have the `lapack' library (-llapack). */
/* #undef HAVE_LIBLAPACK */

/* Define to 1 if you have the `m' library (-lm). */
#define HAVE_LIBM 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Where the data files are ; set in the configure.ac */
//#define LIBDATA_PATH "/usr/local/share/libghemical"
//#define LIBDATA_PATH "d://winlibghemical/libghemical"
#define LIBDATA_PATH "libghemical"
//#define LIBDATA_PATH __FILE__
//#define LIBDATA_PATH __PATH__

/* This is the releasedate of libghemical--it is set in the configure.ac */
#define LIBRELEASEDATE "2005-06-30"

/* This is the version of libghemical to be built--it is set in the
   configure.ac */
#define LIBVERSION "1.90"

/* Name of package */
#define PACKAGE "libghemical"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
//#define PACKAGE_NAME "libghemical"

/* Define to the full name and version of this package. */
//#define PACKAGE_STRING "libghemical 1.90"

/* Define to the one symbol short name of this package. */
//#define PACKAGE_TARNAME "libghemical"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.90"

/* This is the major version of SC (MPQC's underlying library) found by
   configure */
/* #undef SC_MAJOR_VERSION */

/* This is the micro version of SC (MPQC's underlying library) found by
   configure */
/* #undef SC_MICRO_VERSION */

/* This is the minor version of SC (MPQC's underlying library) found by
   configure */
/* #undef SC_MINOR_VERSION */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "1.90"

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */
#define M_PI		3.14159265358979323846

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif
