/* src/appconfig.h.  Generated by configure.  */
/* src/appconfig.h.in.  Generated from configure.ac by autoheader.  */

/* Where the data files are ; set in the configure.ac */
#define APPDATA_PATH "/usr/local/share/ghemical"

/* This is the releasedate of ghemical--it is set in the configure.ac */
#define APPRELEASEDATE "2005-06-30"

/* This is the version of ghemical to be built--it is set in the configure.ac
   */
#define APPVERSION "1.90"

/* Define if you are building a bonobo2 server version */
/* #undef ENABLE_BONOBO */

/* Define if you are building a multithreaded app */
/* #undef ENABLE_THREADS */

/* Define to 1 if you have the <GL/glut.h> header file. */
#define HAVE_GL_GLUT_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `glut' library (-lglut). */
#define HAVE_LIBGLUT 1

/* Define to 1 if you have the `m' library (-lm). */
#define HAVE_LIBM 1

/* Define to 1 if you have the `Xmu' library (-lXmu). */
#define HAVE_LIBXMU 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "ghemical"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "ghemical 1.90"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "ghemical"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.90"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif
