//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ghemical.rc
//
#define IDC_MYICON                      2
#define IDD_GHEMICAL_DIALOG             102
#define IDD_ABOUTBOX                    103
#define IDS_APP_TITLE                   103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDS_HELLO                       106
#define IDI_GHEMICAL                    107
#define IDI_SMALL                       108
#define IDC_GHEMICAL                    109
#define IDR_MAINFRAME                   128
#define IDD_COMMAND_DIALOG              129
#define IDD_DIALOG_TRAJ_VIEW            130
#define IDD_DIALOG_MOL_DYN              131
#define IDD_DIALOG_ATOMLIST_MOLDYN      132
#define IDB_BITMAP_UNCHECKED            133
#define IDB_BITMAP_CHECKED              134
#define IDR_MENU1                       136
#define IDR_MENU_PLOT                   136
#define IDD_DIALOG_SETUP                137
#define IDD_DIALOG_ELEMENT              138
#define IDD_DIALOG_BOND                 139
#define IDD_DIALOG_GEOMOPT              140
#define IDD_DIALOG_SETUP1_QM            141
#define IDD_DIALOG_SETUP1_MM            142
#define IDD_DIALOG_SETUP1_SF            143
#define IDD_DIALOG_SETUP2_QM_MM         144
#define IDD_DIALOG_SETUP2_MM_SF         145
#define IDD_DIALOG_MOL_DYN_TST          146

#define IDC_EDIT_COMMAND                1000
#define IDC_BUTTON_TRAJ_VIEW_BEGIN      1001
#define IDC_BUTTON_TRAJ_VIEW_PREV       1002
#define IDC_BUTTON_TRAJ_VIEW_PLAY       1003
#define IDC_BUTTON_TRAJ_VIEW_NEXT       1004
#define IDC_BUTTON_TRAJ_VIEW_END        1005
#define IDC_CHECK_CONSTANT_E            1006
#define IDC_CHECK_LANGEVIN              1007
#define IDC_BUTTON_BROWSE_TRAJ          1008
#define IDC_EDIT_NSTEPS_H               1009
#define IDC_EDIT_NSTEPS_E               1010
#define IDC_EDIT_NSTEPS_S               1011
#define IDC_EDIT_TEMPERATURE            1012
#define IDC_EDIT_TIMESTEP               1013
#define IDC_EDIT_TRAJFILE               1014
#define IDC_MOL_DYN_ATOM_LIST           1015
#define IDC_BUTTON_BROWSE_INPUT_FRAME   1016
#define IDC_BUTTON_BROWSE_OUTPUT_FRAME  1017
#define IDC_EDIT_DELTA_E                1018
#define IDC_EDIT_INPUT_FRAME_FILE       1019
#define IDC_EDIT_OUTPUT_FRAME_FILE      1020
#define IDC_CHECK_DELTA_E               1021
#define IDC_EDIT_GRAD                   1022
#define IDC_CHECK_GRAD                  1023
#define IDC_EDIT_NSTEPS                 1024
#define IDC_CHECK_NSTEPS                1025
#define IDC_EDIT_DELTA_E_MIN_NSTEPS     1026
#define IDC_RADIO_BOX_OPT_NO            1027
#define IDC_EDIT_GRAVI_GX               1028
#define IDC_RADIO_BOX_OPT_XYZ           1029
#define IDC_EDIT_GRAVI_GY               1030
#define IDC_RADIO_BOX_OPT_XY            1031
#define IDC_EDIT_GRAVI_GZ               1032
#define IDC_RADIO_BOX_OPT_Z             1033
#define IDC_CHECK_CALC_MIN_MAX_COORDINATES_2 1034
#define IDC_CHECK_CALC_MIN_MAX_COORDINATES 1035
#define IDC_CHECK_BOX_OPTIMIZATION      1036
#define IDC_CHECK_BOX_OPTIMIZATION_2    1037
#define IDC_CHECK_MAXWELL_DISTRIBUTION_INIT 1038
#define IDC_CHECK_DONT_MOVE_FIXED_ATOMS 1039
#define IDC_CHECK_LOAD_LAST_FRAME       1040
#define IDC_EDIT_MAXWELL_INIT_TEMPERATURE 1041

#define ID_FILE_INITOG                  32771
#define ID_FILE_INITOG2                 32772
#define ID_VIEW_UPDATEALLVIEWS          32774
#define ID_DO_MOLECULARDYNAMICS         32776
#define ID_FILE_OPEN                    32777
#define ID_MOUSE_DRAW                   32778
#define ID_MOUSE_ERASE                  32779
#define ID_MOUSE_SELECT                 32780
#define ID_MOUSE_ZOOM                   32781
#define ID_MOUSE_CLIPPING               32782
#define ID_MOUSE_TRANSLATEXY            32783
#define ID_MOUSE_TRANSLATEZ             32784
#define ID_MOUSE_ORBITXY                32785
#define ID_MOUSE_ORBITZ                 32786
#define ID_MOUSE_ROTATEXY               32787
#define ID_MOUSE_ROTATEZ                32788
#define ID_MOUSE_MEASURE                32789
#define ID_BUILD_ADDHYDROGENS           32790
#define ID_BUILD_DELETEHYDROGENS        32791
#define ID_BUILD_CLEAR                  32792
#define ID_FILE_SAVEAS                  32793
#define ID_BUILD_SOLVATEBOX             32794
#define ID_BUILD_SOLVATESPHERE          32795
#define ID_DO_TRAJECTORYVIEW            32796
#define ID_RENDER_BALLANDSTICK          32797
#define ID_RENDER_VANDERVAALS           32798
#define ID_RENDER_WIREFRAME             32799
#define ID_RENDER_NOTHING               32800
#define ID_RENDER_CYLINDERS             32801
#define ID_FILE_IMPORT                  32802
#define ID_DO_COMPTORSIONENERGYPLOT1D   32804
#define ID_VIEW_CENTER                  32805
#define ID_FILE                         32806
#define ID_FILE_EXIT                    32807
#define ID_DO_COMPUTETORSIONENERGYPLOT2D 32808
#define ID_FILE_EXPORT                  32809
#define ID_COLOR_ELEMENT                32810
#define ID_COLOR_SEC                    32811
#define ID_COLOR_HYDROPHOBICITY         32812
#define ID_LABEL_INDEX                  32813
#define ID_LABEL_ELEMENT                32814
#define ID_LABEL_FORMALCHARGE           32815
#define ID_LABEL_PARTIALCHARGE          32816
#define ID_LABEL_ATOMTYPE               32817
#define ID_LABEL_BUILDERID              32818
#define ID_LABEL_BONDTYPE               32819
#define ID_LABEL_RESIDUE                32820
#define ID_LABEL_SEC                    32821
#define ID_LABEL_NOTHING                32822
#define ID_Menu                         32823
#define ID_DO_COMPUTEANGLEENERGYPLOT1D  32824
#define ID_SELECT_MODE                  32825
#define ID_SELECT_ATOM                  32826
#define ID_SELECT_RESIDUE               32827
#define ID_SELECT_CHAIN                 32828
#define ID_SELECT_MOLECULE              32829
#define ID_SELECT_SELECTALL             32830
#define ID_SELECT_SELECTNONE            32831
#define ID_SELECT_INVERTSELECTION       32832
#define ID_SELECT_DELETESELECTION       32833
#define ID_BUILD_AMINO                  32834
#define ID_BUILD_NUCLEIC                32835
#define ID_DO_ENTERCOMMAND              32836
#define ID_Menu32837                    32837
#define ID_Menu32838                    32838
#define ID_BUILD_SETUP                  32839
#define ID_DO_SETUP                     32841
#define ID_DO_ELEMENT                   32842
#define ID_DO_ELEMENTSTABLE             32843
#define ID_DO_BONDTYPE                  32844
#define ID_VIEW_PERSPECTIVE             32845
#define ID_DO_SORTGROUPS                32847
#define ID_DO_RANDOMSEARCH              32848
#define ID_DO_SYSTEMATICSEARCH          32849
#define ID_DO_MONTECARLOSEARCH          32850
#define ID_DO_COMPUTEENERGY             32851
#define ID_DO_STATIONARYSTATESEARCH     32852
#define ID_DO_TRANSITIONSTATESEARCH     32854
#define ID_DO_POPANAELECTROSTATIC       32855
#define ID_DO_SETORBITAL                32856
#define ID_DO_SETFORMALCHARGE           32857
#define ID_VIEW_ADDENERGYLEVELDIAGRAMVIEW 32858
#define ID_Menu32859                    32859
#define ID_DO_D                         32860
#define ID_DO_D32861                    32861
#define ID_DO_GEOMETRYOPTIMIZATION      32862
#define ID_DO_TRAJECTORY                32863
#define ID_TRAJECTORY_VIEW              32864
#define ID_TRAJECTORY_VIEWANGLEPLOT     32865
#define ID_TRAJECTORY_SETTOTALFRAMES    32866
#define ID_FILE_SAVEAS32867             32867
#define ID_FILE_SAVEBOX                 32868
#define ID_FILE_LOADBOX                 32869
#define ID_FILE_SAVESELECTED            32870
#define ID_FILE_LOADSELECT              32871
#define ID_TRAJECTORY_VIEWDISTANCEPLOT  32873
#define ID_DO_TRAJECTORYVIEWKINETICENERGYPLOT 32875
#define ID_TRAJECTORY_VIEW_POTENCIAL_ENERGY_PLOT 32876
#define ID_SELECTEDATOMS_LOCK           32877
#define ID_SELECTEDATOMS_UNLOCK         32878
#define ID_SELECTEDATOMS_SETASSOLVENT   32879
#define ID_SELECTEDATOMS_UNSETASSOLVENT 32880
#define ID_SELECTEDATOMS_SETUNDERGRAVI  32881
#define ID_SELECTEDATOMS_UNSETUNDERGRAVI 32882
#define ID_BUILD_NEMATICBOX             32883
#define ID_SELECT_SELECTLOCKEDATOMS     32884
#define ID_DO_COMPFORMULA               32885
#define ID_DO_COMPDENSITY               32886
#define ID_SELECTEDATOMS_UNSETASWORKING 32889
#define ID_SELECTEDATOMS_SETASWORKING   32890
#define ID_SELECTEDATOMS_SETASSPECIAL   32891
#define ID_SELECTEDATOMS_UNSETASSPECIAL 32892
#define ID_SELECT_SELECTWORKINGATOMS    32893
#define ID_SELECT_SELECTSPECIALATOMS    32894
#define ID_SELECT_SELECTSOLVENTATOMS    32895
#define ID_SELECT_SELECTUNDERGRAVIATOMS 32896
#define ID_MOUSE_SETMOLECULARAXIS       32897
#define ID_SELECT_SELECTMOLECULARAXISES 32899
#define ID_FILE_SAVEMOLECULARAXISES     32900
#define ID_FILE_LOADMOLECULARAXISES     32901
#define ID_BUILD_CLEARMOLECULARAXISES   32902
#define ID_TRAJECTORY_NEMATICORDERPARAMETERPLOT 32903
#define ID_TRAJECTORY_CONCATTRAJFILES   32904
#define ID_TRAJECTORY_VIEWCOORDINATEDIFFERENCEPLOT 32905
#define ID_TRAJECTORY_VIEWCOORDINATEPLOT1 32906
#define ID_TRAJECTORY_VELONCITYDISTRIBUTION2D 32908
#define ID_DO_MOLECULARDYNAMICS_TST     32909
#define ID_SELECTEDATOMS_SMOOTHLYLOCK   32910
#define ID_SELECTEDATOMS_SMOOTHLYUNLOCK 32911
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32912
#define _APS_NEXT_CONTROL_VALUE         1035
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
